# Generated by Django 4.1.8 on 2023-04-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
    ]
