# Generated by Django 4.1.8 on 2023-04-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_thecompany_delete_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thecompany',
            options={'managed': False, 'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
    ]
