# Generated by Django 4.1.8 on 2023-04-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_thecompany_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='thecompany',
            table='company',
        ),
    ]
