# Generated by Django 4.1.8 on 2023-04-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_thecompany_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='thecompany',
            table='the_company',
        ),
    ]
